programa: main.c rush.c translator.c read_file.c ft_atoi.c str_libs.c str_to_vars.c test.c
	gcc  main.c rush.c translator.c read_file.c ft_atoi.c str_libs.c str_to_vars.c numbers.c -o rush-02
fclean:
	rm -f rush-02